---
title: "Drug Related Deaths in Scotland 2017"
author: "Christian Cole"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(readxl)
library(reshape2)
library(ggplot2)
library(tibble)

# default region colours
reg.colours = c("#4D4D4D", "#AEAEAE")

# The colour-blind palette with grey:
myPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

# read data - download first as read_excel() can't do URLs
xlfile = tempfile(fileext = '.xlsx')
download.file("https://www.nrscotland.gov.uk/files//statistics/drug-related-deaths/17/drug-related-deaths-17-tabs-figs.xlsx", xlfile, mode="wb")

```

## Tab {.tabset}

### Table 2

```{r t2}
# read data
table8.dat = read_excel(xlfile, sheet = 4, col_names=FALSE)

# extract core data and convert to numbers
dat = table8.dat[36:43,c(1,3:7)]
dat = data.frame(apply(dat, 2, as.numeric))

# add colnames
colnames(dat) <- c('Year','Drug Abuse','Accidental Poisoning','Suicide','Assault by Drugs','Undetermined')

# remove averages row and save
mean13.17 = dat[8,]
dat = dat[-8,]

year.totals = dat.m %>% group_by(Year) %>% summarise(Total = sum(value))

# factorise the years to turn into a label and melt
dat$Year <- factor(dat$Year)
dat.m = melt(dat)

ggplot(dat.m, aes(x=Year, y=value, fill=variable)) + 
  ggtitle("Underlying Cause of Death") +
  ylab("No. Deaths") +
  geom_col() +
  geom_text(aes(x=Year, y=Total+28, label = Total, fill = NULL), data=year.totals, size=2.8) +
  scale_fill_manual(values = myPalette) +
  theme_minimal() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.title = element_blank())

```

### Table 3

```{r t3}
# read data
table.dat = read_excel(xlfile, sheet = 5, col_names=FALSE)

# extract core data and convert to numbers
dat = table.dat[23:32,c(1,3:14)]
dat = data.frame(apply(dat, 2, as.numeric))

colnames(dat) <- c('Year','Heroin/morphine','Methodone','Heroin or OST','Codeine', 'Dihydrocodeine', 'Any opiate', 'Any benzodiazepine', 'Diazepam', 'Cocaine', 'Ecstasy', 'Amphetamines', 'Alcohol')

# heroin or OST and any opiate are not very informative
# as they're just a combination of the others (accounting for
# individual cases)
dat = dat[,-7]
dat = dat[,-4]

# combine the codeine/dihydrocodeine cols and remove
dat = data.frame(dat, Codeines = dat$Codeine + dat$Dihydrocodeine)
dat = dat[,-5]
dat = dat[,-4]

opiates = dat[,c(1:3,10)]

# factorise the years to turn into a label and melt
dat$Year <- factor(dat$Year)
dat.m = melt(dat)

ggplot(dat.m, aes(x=Year, y=value, group=variable, colour=variable)) +
  ggtitle("Drugs Implicated in Death", subtitle = 'Opiates') +
  ylab("No. of Deaths") +
  geom_line(size=1.1) +
  #scale_color_manual(values = myPalette) +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank())

```


### Table 8

```{r t8}
# read data
table8.dat = read_excel(xlfile, sheet = 10, col_names=FALSE)

# extract core data and convert to numbers
dat = table8.dat[10:27,2:6]
dat = data.frame(apply(dat, 2, as.numeric))

# extract mean for last five years
yr5mean = as.numeric(table8.dat[29,7])

# add labels
names(dat) <- c("15-24","25-34","35-44","45-54","55-64")
dat = cbind(Year=factor(seq(2000,2017)), dat)

# melt data and plot
# note: dashed line is for average deaths 2012-2016 for ages 15-64
dat.m = melt(dat, variable.name = "Age")
ggplot(dat.m, aes(x=Year, y=value, group=Age, colour=Age)) + 
  geom_hline(yintercept = yr5mean, colour="grey", linetype="dashed") + 
  geom_line(size=1.2) + 
  ylab("Deaths per 1000 population") + 
  annotate("text", label="Mean 2013-2017", x=16.8,y=yr5mean-0.015,size=3,colour="grey") +
  scale_x_discrete(breaks=seq(2000,2016,2)) + 
  scale_color_manual(values=myPalette) +
  ggtitle("Death Rates by Age") +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())



```

